name: Build PDF from Markdown

on:
  push:
    branches:
      - ASO-1/programacion

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended texlive-latex-extra texlive-lang-spanish fonts-liberation fonts-noto
          sudo fc-cache -fv

      - name: Convert README.md to PDF
        run: |
          pandoc README.md \
          --template=template.tex \
          --pdf-engine=xelatex \
          --lua-filter=needspace.lua \
          -V mainfont="Liberation Sans" \
          -V fallbackfont="Noto Sans" \
          -V TITLE="Administración de Sistemas Operativos" \
          -V CODIGO="0363" \
          -V CICLO="Ciclo Formativo de Grado Superior de Administración de Sistemas Informáticos en Red" \
          -V REVISION="17/10/2025" \
          -o programacion_ASO.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: programacion_ASO
          path: programacion_ASO.pdf